// This file will be auto-generated by: npx supabase gen types typescript --local
// For now, provide a minimal placeholder type.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          nif: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          logo_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          nif?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          nif?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      parks: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          code: string;
          address: string | null;
          phone: string | null;
          email: string | null;
          license_number: string | null;
          license_expiry: string | null;
          is_active: boolean;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          code: string;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          license_number?: string | null;
          license_expiry?: string | null;
          is_active?: boolean;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          code?: string;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          license_number?: string | null;
          license_expiry?: string | null;
          is_active?: boolean;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          org_id: string | null;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          preferred_locale: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          org_id?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          preferred_locale?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          preferred_locale?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_park_access: {
        Row: {
          id: string;
          user_id: string;
          park_id: string;
          role: "admin" | "park_manager" | "scale_operator" | "classifier" | "commercial_manager";
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          park_id: string;
          role: "admin" | "park_manager" | "scale_operator" | "classifier" | "commercial_manager";
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          park_id?: string;
          role?: "admin" | "park_manager" | "scale_operator" | "classifier" | "commercial_manager";
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          org_id: string | null;
          park_id: string | null;
          user_id: string | null;
          action: string;
          table_name: string;
          record_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id?: string | null;
          park_id?: string | null;
          user_id?: string | null;
          action: string;
          table_name: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          park_id?: string | null;
          user_id?: string | null;
          action?: string;
          table_name?: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      ler_codes: {
        Row: {
          id: string;
          code: string;
          chapter: string;
          sub_chapter: string | null;
          description_pt: string;
          description_en: string | null;
          is_hazardous: boolean;
          is_mirror: boolean;
          parent_code: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          chapter: string;
          sub_chapter?: string | null;
          description_pt: string;
          description_en?: string | null;
          is_hazardous?: boolean;
          is_mirror?: boolean;
          parent_code?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          chapter?: string;
          sub_chapter?: string | null;
          description_pt?: string;
          description_en?: string | null;
          is_hazardous?: boolean;
          is_mirror?: boolean;
          parent_code?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      park_ler_authorizations: {
        Row: {
          id: string;
          park_id: string;
          ler_code_id: string;
          operation_type: "reception" | "treatment" | "storage" | "valorization" | "elimination";
          max_capacity_kg: number | null;
          annual_limit_kg: number | null;
          is_active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          park_id: string;
          ler_code_id: string;
          operation_type?: "reception" | "treatment" | "storage" | "valorization" | "elimination";
          max_capacity_kg?: number | null;
          annual_limit_kg?: number | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          park_id?: string;
          ler_code_id?: string;
          operation_type?: "reception" | "treatment" | "storage" | "valorization" | "elimination";
          max_capacity_kg?: number | null;
          annual_limit_kg?: number | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      storage_areas: {
        Row: {
          id: string;
          park_id: string;
          code: string;
          name: string;
          area_type: "physical" | "logical" | "vfv" | "sorting_line" | "warehouse";
          capacity_kg: number | null;
          current_stock_kg: number;
          allowed_ler_codes: string[] | null;
          location_description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          park_id: string;
          code: string;
          name: string;
          area_type?: "physical" | "logical" | "vfv" | "sorting_line" | "warehouse";
          capacity_kg?: number | null;
          current_stock_kg?: number;
          allowed_ler_codes?: string[] | null;
          location_description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          park_id?: string;
          code?: string;
          name?: string;
          area_type?: "physical" | "logical" | "vfv" | "sorting_line" | "warehouse";
          capacity_kg?: number | null;
          current_stock_kg?: number;
          allowed_ler_codes?: string[] | null;
          location_description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      scales: {
        Row: {
          id: string;
          park_id: string;
          code: string;
          name: string;
          scale_type: "platform" | "floor" | "bench" | "crane";
          max_capacity_kg: number;
          min_capacity_kg: number;
          precision_kg: number;
          last_calibration: string | null;
          next_calibration: string | null;
          calibration_certificate: string | null;
          mock_endpoint_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          park_id: string;
          code: string;
          name: string;
          scale_type?: "platform" | "floor" | "bench" | "crane";
          max_capacity_kg: number;
          min_capacity_kg?: number;
          precision_kg?: number;
          last_calibration?: string | null;
          next_calibration?: string | null;
          calibration_certificate?: string | null;
          mock_endpoint_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          park_id?: string;
          code?: string;
          name?: string;
          scale_type?: "platform" | "floor" | "bench" | "crane";
          max_capacity_kg?: number;
          min_capacity_kg?: number;
          precision_kg?: number;
          last_calibration?: string | null;
          next_calibration?: string | null;
          calibration_certificate?: string | null;
          mock_endpoint_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "admin" | "park_manager" | "scale_operator" | "classifier" | "commercial_manager";
      ler_operation_type: "reception" | "treatment" | "storage" | "valorization" | "elimination";
      area_type: "physical" | "logical" | "vfv" | "sorting_line" | "warehouse";
      scale_type: "platform" | "floor" | "bench" | "crane";
    };
  };
}
